### ISSUE TITLE
bug: nav doesn't work

### ISSUE THREAD

**Issue by yimingwangdell** [stevearc/aerial.nvim#403] opened 2024-08-22 02:43 UTC
### Neovim version (nvim -v)

latest

### Operating system/version

debian

### Output of :AerialInfo

as normal

### Describe the bug

in nav window, search function name, 'n' keymap doesn't work and cannot jump to next. but "N" works as normal.

### What is the severity of this bug?

minor (annoyance)

### Steps To Reproduce

any

### Expected Behavior

'n' work as expected.

### Minimal init.lua

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  {
    "stevearc/aerial.nvim",
    config = function()
      require("aerial").setup({
        -- add your aerial config here
      })
    end,
  },
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    config = function()
      require("nvim-treesitter.configs").setup({
        ensure_installed = { "c", "lua" },
        auto_install = true,
        highlight = { enable = true },
      })
    end,
  },
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by matu3ba** [comment] 2024-09-08 23:01
The bug report is missing the neovim version and "as normal" does not show if either treesitter or lsp is available.
Are your personal keymaps also missing xor did you test that the issue reproduces? There are no steps filled in "Steps To Reproduce", which makes me suspect there is something missing.

Otherwise, the most likely cause is a conflicting keymap from your side.

Did you rule out via `:map`, `:Telescope keymaps` and `:checkhealth` with which-key installed that you have no conflicting keymap?
which-key setup via
```lua
  {
    'folke/which-key.nvim',
    config = function() require('which-key').setup() end,
  }, -- :Telescope builtin.keymaps
```

**Comment by yimingwangdell** [comment] 2024-09-09 07:38
@matu3ba I didn't remap the "n" in normal mode
![image](https://github.com/user-attachments/assets/f577baca-d7ac-451e-ba10-f12fd6961195)

**Comment by matu3ba** [comment] 2024-09-10 21:24
> could you check if this function works in your side?

The default is mapped to `}` and `{` inside Aerial preview and I have mapped a global one via
```lua
    vim.keymap.set('n', '<', '<cmd>AerialPrev<CR>', { buffer = bufnr })
    vim.keymap.set('n', '>', '<cmd>AerialNext<CR>', { buffer = bufnr })
```

The keymap `n` (the second field) is not mapped on default. I can skim through your dotfiles, if you have them hosted somewhere. However, the behavior you are seeing sounds expected to me.
You can see my config here: https://github.com/matu3ba/dotfiles/blob/84ac247730e1e43e067838a7506684943effa5a0/.config/nvim/lua/my_aerial.lua

**Comment by yimingwangdell** [comment] 2024-09-11 05:14
@matu3ba   myconfig 
https://github.com/yimingwangdell/vimrc/blob/master/nvim/init.vim

**Comment by yimingwangdell** [comment] 2024-09-11 05:22
@matu3ba but "n' is a default behavior to jump to next item if I use "/' to search something. also "N" works as expected.

**Comment by matu3ba** [comment] 2024-09-11 07:21
Via `rg "\bn\b" .\nvim\` I found that
nvim\lua\config\plugins\editsearch.lua:11 shows
```
			vim.api.nvim_set_keymap('n', 'n',
				[[<Cmd>execute('normal! ' . v:count1 . 'n')<CR><Cmd>lua require('hlslens').start()<CR>]],
				kopts)
```
which is loaded in
```lua
nvim\lua\config\plugins.lua
62:     require("config.plugins.editsearch"),
```

**Comment by yimingwangdell** [comment] 2024-09-11 09:02
@matu3ba I just use single init.vim now, the _init.lua and all .lua file is not used anymore.

**Comment by stevearc** [comment] 2024-09-11 16:11
I believe this was caused by accidentally forcing the cursor position to column 0. Should be fixed now

**Closed by stevearc** 2024-09-11 16:11 UTC
Labels: bug
