### ISSUE TITLE
render.lua:225 Expected lua string

### ISSUE THREAD

**Issue by yimingwangdell** [stevearc/aerial.nvim#296] opened 2023-09-23 03:24 UTC
**Language**: go
**AerialInfo**: error

traceback:
render.lua 225
window.lua 497
autocommands.lua 134

reproduce: open any go file, open aerial with toggle, and  run :q! to quit, then I cant move with jk in go source code anymore.

**Comment by stevearc** [comment] 2023-09-23 08:08
Does not repro for me. Closing for insufficient information. If you can get a minimal config that reproduces the issue, feel free to reopen.

**Closed by stevearc** 2023-09-23 08:08 UTC

**Comment by yimingwangdell** [comment] 2023-09-25 02:00
@stevearc  it's :q! not :q

**Comment by stevearc** [comment] 2023-09-25 04:50
Let me know if you can get the repro with a minimal config file, because it doesn't repro in my config.

**Comment by yimingwangdell** [comment] 2023-09-25 06:03
{
		"stevearc/stickybuf.nvim",
		config = function()
			require("stickybuf").setup({
				-- This function is run on BufEnter to determine pinning should be activated
				get_auto_pin = function(bufnr)
					-- You can return "bufnr", "buftype", "filetype", or a custom function to set how the window will be pinned
					-- The function below encompasses the default logic. Inspect the source to see what it does.
					return require("stickybuf").should_auto_pin(bufnr)
				end
			})
		end
	},
	{
		"stevearc/aerial.nvim",
		lazy = false,
		config = function()
			require("aerial").setup({
				on_attach = function(bufnr)
					-- Jump forwards/backwards with '{' and '}'
					vim.keymap.set('n', '[[', '<cmd>AerialPrev<CR>', { buffer = bufnr })
					vim.keymap.set('n', ']]', '<cmd>AerialNext<CR>', { buffer = bufnr })
				end
			})
			vim.keymap.set('n', 'tg', '<cmd>AerialToggle<CR>')
		end
	}


@stevearc
