### ISSUE TITLE
E5108: Error executing lua ...m/site/pack/packer/opt/aerial.nvim/lua/aerial/window.lua:273: Invalid window id: 1003

### ISSUE THREAD

**Issue by reubenwong97** [stevearc/aerial.nvim#151] opened 2022-09-14 16:31 UTC
Hello,
When I try to view the symbols outline for files that are in languages other than lua, like python or rust, I get the following error:

```lua
E5108: Error executing lua ...m/site/pack/packer/opt/aerial.nvim/lua/aerial/window.lua:273: Invalid window id: 1003
stack traceback:
        [C]: in function 'nvim_set_current_win'
        ...m/site/pack/packer/opt/aerial.nvim/lua/aerial/window.lua:273: in function 'open'
        ...m/site/pack/packer/opt/aerial.nvim/lua/aerial/window.lua:307: in function 'toggle'
        ...vim/site/pack/packer/opt/aerial.nvim/lua/aerial/init.lua:90: in function 'toggle'
        [string "luaeval()"]:1: in main chunk
```

For aerial.nvim and treesitter, I am using the default setup from Astronvim. I already performed `:TSInstall` for those languages.

Thank you.

**Comment by stevearc** [comment] 2022-09-14 16:51
The line it's erroring on indicates that somehow the aerial window was created, but then was closed or otherwise made invalid immediately. If you do `:AerialToggle!` (with the `!`) what happens?

Can you give me an example of one of the languages that you see this happening for? And what is the output of `:AerialInfo`?

**Comment by reubenwong97** [comment] 2022-09-15 01:39
Hi @stevearc ,
Thanks for getting back to me! When I do `:AerialToggle!`, nothing happens. This happens for python and rust, 2 languages I'm using.

`:AerialInfo` for python:
```
Aerial Info
-----------
Filetype: python
Configured backends:
  lsp (supported) (attached)
  treesitter (supported)
  markdown (not supported) [Filetype is not markdown]
Show symbols: all symbols
```

`:AerialInfo` for rust:
```
Aerial Info
-----------
Filetype: rust
Configured backends:
  lsp (supported) (attached)
  treesitter (supported)
  markdown (not supported) [Filetype is not markdown]
Show symbols: all symbols
```

Thank you!

**Comment by stevearc** [comment] 2022-09-15 22:15
I tried installing the latest version of AstroNvim with the following in my `user/init.lua`:
```lua
return {
  lsp = {
    servers = {
      "pyright",
    },
  },
}
```
I could not reproduce the issue in either nvim v0.7.2 or nightly when opening a python file. I've also taken another pass at examining the code, and I can't see how a bad window reference could get there unless some autocmds triggered that did something unexpected.

A bunch of different debugging ideas:
- Try with the minimal user config I provided
- List the version of Neovim you're using
- List the version of AstroNvim and aerial that you're using
- Try using the treesitter backend (`aerial.setup({ backends = {"treesitter", "lsp"} })`)
- Shot in the dark: try [commenting out these lines](https://github.com/stevearc/aerial.nvim/blob/f7d6ca898b32f00c29037d399ab6bba77b2a2ad9/lua/aerial/window.lua#L38-L40)

**Comment by reubenwong97** [comment] 2022-09-16 02:26
Thanks @stevearc ,
My configuration for python is pretty bare-bones, though I use `pylsp-language-server` installed through `mason.nvim`.
I am using Neovim `v0.7.2`.
I am using Astronvim `v1.9.2`.
I am not too sure how to check the version of aerial I am using xD, but it is the latest version when updating with `:PackerSync`.

When I used the treesitter backend, it was reflected as attached in `:AerialInfo`, but still ran into the same error.

When commenting out the lines you mentioned, `:AerialToggle!` opened a blank read-only buffer on the right side of my screen with no symbols.

Thank you :)

**Comment by stevearc** [comment] 2022-09-16 10:37
Well, I'm confused. I should be on the exact same version and config as you, but I still can't get the issue to reproduce. At this point we're out of good options, so here's what we fall back to:

I have a vague suspicion that you have a rogue autocmd that triggers on BufWinEnter, WinEnter, or similar that is closing the window. I have no idea where it would come from, because theoretically we have the same config, but this is the only thing that makes sense to me. I have taken a blind shot at changing something inside aerial that may avoid running into it; you can try it out by using the branch `stevearc-defer-filetype`. In the aerial config of `lua/core/plugins.lua`, add `branch = "stevearc-defer-filetype"` (around line 173) and re-run `:PackerSync`. Hopefully it will help, but I'm flying blind so who knows.

The other unfortunate option is to fiddle with your config until you find the conflict. First, I'd recommend a sanity check that the issue _does not_ reproduce when using this minimal init.lua:

```lua
local install_path = vim.fn.stdpath 'data' .. '/site/pack/packer/start/packer.nvim'
local is_bootstrap = false
if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  is_bootstrap = true
  vim.fn.execute('!git clone https://github.com/wbthomason/packer.nvim ' .. install_path)
  vim.cmd [[packadd packer.nvim]]
end

require('packer').startup(function(use)
  use 'wbthomason/packer.nvim'
  use 'nvim-treesitter/nvim-treesitter'
  use 'stevearc/aerial.nvim'

  if is_bootstrap then
    require('packer').sync()
  end
end)

if is_bootstrap then
  print '=================================='
  print '    Plugins are being installed'
  print '    Wait until Packer completes,'
  print '       then restart nvim'
  print '=================================='
  return
end

require('aerial').setup()

require('nvim-treesitter.configs').setup {
  ensure_installed = {'lua', 'python', 'rust'},

  highlight = { enable = true },
}
```

Assuming it doesn't, it's just a matter of progressively adding back pieces of the config until you see the issue again. Easier said than done; usually it's quite difficult to chop up a config into pieces without causing a bunch of unrelated issues, but maybe AstroNvim is modular enough to make that approachable.

**Comment by reubenwong97** [comment] 2022-09-16 13:14
Hey @stevearc ,

I tried using that branch instead, but got the same error again.
```lua
E5108: Error executing lua ...m/site/pack/packer/opt/aerial.nvim/lua/aerial/window.lua:271: Failed to switch to window 10
03
stack traceback:
        [C]: in function 'nvim_set_current_win'
        ...m/site/pack/packer/opt/aerial.nvim/lua/aerial/window.lua:271: in function 'open'
        ...m/site/pack/packer/opt/aerial.nvim/lua/aerial/window.lua:305: in function 'toggle'
        ...vim/site/pack/packer/opt/aerial.nvim/lua/aerial/init.lua:90: in function 'toggle'
        [string "luaeval()"]:1: in main chunk
```

I will attempt to build back the config as you suggested, but will just place my `init.lua` here as a reference. At this stage, I'm thankful you took so much time to try and help me, and if its unfixable, its alright xD. Thanks so much.

```lua
--              AstroNvim Configuration Table
-- All configuration changes should go inside of the table below
-- You can think of a Lua "table" as a dictionary like data structure the
-- normal format is "key = value". These also handle array like data structures
-- where a value with no key simply has an implicit numeric key
local config = {

  -- Configure AstroNvim updates
  updater = {
    remote = "origin", -- remote to use
    channel = "nightly", -- "stable" or "nightly"
    version = "latest", -- "latest", tag name, or regex search like "v1.*" to only do updates before v2 (STABLE ONLY)
    branch = "main", -- branch name (NIGHTLY ONLY)
    commit = nil, -- commit hash (NIGHTLY ONLY)
    pin_plugins = nil, -- nil, true, false (nil will pin plugins on stable only)
    skip_prompts = false, -- skip prompts about breaking changes
    show_changelog = true, -- show the changelog after performing an update
    auto_reload = false, -- automatically reload and sync packer after a successful update
    auto_quit = false, -- automatically quit the current session after a successful update
    -- remotes = { -- easily add new remotes to track
    --   ["remote_name"] = "https://remote_url.come/repo.git", -- full remote url
    --   ["remote2"] = "github_user/repo", -- GitHub user/repo shortcut,
    --   ["remote3"] = "github_user", -- GitHub user assume AstroNvim fork
    -- },
  },

  -- Set colorscheme to use
  -- colorscheme = "default_theme",
  colorscheme = "catppuccin",

  -- Override highlight groups in any theme
  highlights = {
    -- duskfox = { -- a table of overrides/changes to the default
    --   Normal = { bg = "#000000" },
    -- },
    default_theme = function(highlights) -- or a function that returns a new table of colors to set
      local C = require "default_theme.colors"

      highlights.Normal = { fg = C.fg, bg = C.bg }
      return highlights
    end,
  },

  -- set vim options here (vim.<first_key>.<second_key> =  value)
  options = {
    opt = {
      relativenumber = true, -- sets vim.opt.relativenumber
    },
    g = {
      mapleader = ",", -- sets vim.g.mapleader
      rustfmt_command = "$HOME/.cargo/bin/rustfmt", -- sets vim.g.rustfmt_command
      rustfmt_autosave = 1,
      catppuccin_flavour = "mocha", -- latte, frappe, macchiato, mocha
    },
  },
  -- If you need more control, you can use the function()...end notation
  -- options = function(local_vim)
  --   local_vim.opt.relativenumber = true
  --   local_vim.g.mapleader = " "
  --   local_vim.opt.whichwrap = vim.opt.whichwrap - { 'b', 's' } -- removing option from list
  --   local_vim.opt.shortmess = vim.opt.shortmess + { I = true } -- add to option list
  --
  --   return local_vim
  -- end,

  -- Default theme configuration
  default_theme = {
    -- set the highlight style for diagnostic messages
    diagnostics_style = { italic = true },
    -- Modify the color palette for the default theme
    colors = {
      fg = "#abb2bf",
      bg = "#1e222a",
    },
    -- enable or disable highlighting for extra plugins
    plugins = {
      aerial = true,
      beacon = false,
      bufferline = true,
      dashboard = true,
      highlighturl = true,
      hop = false,
      indent_blankline = true,
      lightspeed = false,
      ["neo-tree"] = true,
      notify = true,
      ["nvim-tree"] = false,
      ["nvim-web-devicons"] = true,
      rainbow = true,
      symbols_outline = false,
      telescope = true,
      vimwiki = false,
      ["which-key"] = true,
    },
  },

  -- Diagnostics configuration (for vim.diagnostics.config({...}))
  diagnostics = {
    virtual_text = true,
    underline = true,
  },

  -- Extend LSP configuration
  lsp = {
    skip_setup = { "rust_analyzer" },
    -- enable servers that you already have installed without mason
    servers = {
      -- "pyright"
    },
    -- easily add or disable built in mappings added during LSP attaching
    mappings = {
      n = {
        -- ["<leader>lf"] = false -- disable formatting keymap
        ["gD"] = { vim.lsp.buf.declaration, desc = "Declaration" },
        ["gd"] = { vim.lsp.buf.definition, desc = "Definition" },
        ["K"] = { vim.lsp.buf.hover, desc = "Hover" },
        ["gi"] = { vim.lsp.buf.implementation, desc = "Go-to implementation" },
        ["<C-k>"] = { vim.lsp.buf.signature_help, desc = "Signature help" },
        ["<space>wa"] = { vim.lsp.buf.add_workspace_folder, desc = "Add workspace folder" },
        ["<space>wr"] = { vim.lsp.buf.remove_workspace_folder, desc = "Remove workspace folder" },
        ["<space>wl"] = {
          function() print(vim.inspect(vim.lsp.buf.list_workspace_folders())) end,
          desc = "List workspace folders",
        },
        ["<space>D"] = { vim.lsp.buf.type_definition, desc = "Show type definition" },
        ["<space>rn"] = { vim.lsp.buf.rename, desc = "Rename symbols" },
        ["<space>ca"] = { vim.lsp.buf.code_action, desc = "Code actions" },
        ["gr"] = { vim.lsp.buf.references, desc = "Go-to references" },
        ["<space>f"] = { vim.lsp.buf.formatting, desc = "Format buffer" },
      },
    },
    -- add to the global LSP on_attach function
    on_attach = function(client, bufnr) vim.api.nvim_buf_set_option(bufnr, "omnifunc", "v:lua.vim.lsp.omnifunc") end,

    -- override the mason server-registration function
    -- server_registration = function(server, opts)
    --   require("lspconfig")[server].setup(opts)
    -- end,

    -- Add overrides for LSP server settings, the keys are the name of the server
    ["server-settings"] = {
      -- example for addings schemas to yamlls
      -- yamlls = { -- override table for require("lspconfig").yamlls.setup({...})
      --   settings = {
      --     yaml = {
      --       schemas = {
      --         ["http://json.schemastore.org/github-workflow"] = ".github/workflows/*.{yml,yaml}",
      --         ["http://json.schemastore.org/github-action"] = ".github/action.{yml,yaml}",
      --         ["http://json.schemastore.org/ansible-stable-2.9"] = "roles/tasks/*.{yml,yaml}",
      --       },
      --     },
      --   },
      -- },
      -- Example disabling formatting for a specific language server
      -- gopls = { -- override table for require("lspconfig").gopls.setup({...})
      --   on_attach = function(client, bufnr)
      --     client.resolved_capabilities.document_formatting = false
      --   end
      -- }
    },
  },

  -- Mapping data with "desc" stored directly by vim.keymap.set().
  --
  -- Please use this mappings table to set keyboard mapping since this is the
  -- lower level configuration and more robust one. (which-key will
  -- automatically pick-up stored data by this setting.)
  mappings = {
    -- first key is the mode
    n = {
      -- second key is the lefthand side of the map
      -- mappings seen under group name "Buffer"
      ["<leader>bb"] = { "<cmd>tabnew<cr>", desc = "New tab" },
      ["<leader>bc"] = { "<cmd>BufferLinePickClose<cr>", desc = "Pick to close" },
      ["<leader>bj"] = { "<cmd>BufferLinePick<cr>", desc = "Pick to jump" },
      ["<leader>bt"] = { "<cmd>BufferLineSortByTabs<cr>", desc = "Sort by tabs" },
      -- quick save
      -- ["<C-s>"] = { ":w!<cr>", desc = "Save File" },  -- change description but the same command
      [";"] = { ":", desc = "Convenience for command mode" },
      ["<C-space>"] = { "<cmd>RustHoverActions<cr>", desc = "To get floating box" },
      ["<space>e"] = { vim.diagnostic.open_float, desc = "Open float" },
      ["[d"] = { vim.diagnostic.goto_prev, desc = "Go-to prev" },
      ["]d"] = { vim.diagnostic.goto_next, desc = "" },
      ["<space>q"] = { vim.diagnostic.setloclist, desc = "Set loc list" },
      ["<space>("] = { "viWc()<Esc>P", desc = "Wrap a Word with parenthesis" },
    },
    t = {
      -- setting a mapping to false will disable it
      -- ["<esc>"] = false,
    },
  },

  -- Configure plugins
  plugins = {
    init = {
      -- You can disable default plugins as follows:
      -- ["goolord/alpha-nvim"] = { disable = true },

      -- You can also add new plugins here as well:
      -- Add plugins, the packer syntax without the "use"
      -- { "andweeb/presence.nvim" },
      -- {
      --   "ray-x/lsp_signature.nvim",
      --   event = "BufRead",
      --   config = function()
      --     require("lsp_signature").setup()
      --   end,
      -- },

      -- We also support a key value style plugin definition similar to NvChad:
      -- ["ray-x/lsp_signature.nvim"] = {
      --   event = "BufRead",
      --   config = function()
      --     require("lsp_signature").setup()
      --   end,
      -- },
      -- Catppuccin theme
      { "catppuccin/nvim" },
      -- Rust support
      {
        "rust-lang/rust.vim",
      },
      {
        "simrat39/rust-tools.nvim",
        after = { "mason-lspconfig.nvim" },
        -- Is configured via the server_registration_override installed below!
        config = function()
          require("rust-tools").setup {
            server = astronvim.lsp.server_settings "rust_analyzer",
            tools = {
              inlay_hints = {
                parameter_hints_prefix = "?  ",
                other_hints_prefix = "?  ",
              },
            },
          }
        end,
      },
      -- Crates support, staying on stable version
      {
        "saecki/crates.nvim",
        tag = "v0.2.1",
        requires = { "nvim-lua/plenary.nvim" },
        config = function() require("crates").setup() end,
      },
    },
    -- All other entries override the require("<key>").setup({...}) call for default plugins
    ["null-ls"] = function(config) -- overrides `require("null-ls").setup(config)`
      -- config variable is the default configuration table for the setup functino call
      local null_ls = require "null-ls"
      -- Check supported formatters and linters
      -- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/formatting
      -- https://github.com/jose-elias-alvarez/null-ls.nvim/tree/main/lua/null-ls/builtins/diagnostics
      config.sources = {
        -- Set a formatter
        null_ls.builtins.formatting.stylua,
        null_ls.builtins.formatting.prettier,
      }
      -- set up null-ls's on_attach function
      -- NOTE: You can remove this on attach function to disable format on save
      config.on_attach = function(client)
        if client.resolved_capabilities.document_formatting then
          vim.api.nvim_create_autocmd("BufWritePre", {
            desc = "Auto format before save",
            pattern = "<buffer>",
            callback = vim.lsp.buf.formatting_sync,
          })
        end
      end
      return config -- return final config table to use in require("null-ls").setup(config)
    end,
    treesitter = { -- overrides `require("treesitter").setup(...)`
      ensure_installed = { "lua" },
    },
    -- use mason-lspconfig to configure LSP installations
    ["mason-lspconfig"] = { -- overrides `require("mason-lspconfig").setup(...)`
      ensure_installed = { "sumneko_lua", "rust_analyzer" },
    },
    -- use mason-tool-installer to configure DAP/Formatters/Linter installation
    ["mason-tool-installer"] = { -- overrides `require("mason-tool-installer").setup(...)`
      ensure_installed = { "prettier", "stylua" },
    },
    packer = { -- overrides `require("packer").setup(...)`
      compile_path = vim.fn.stdpath "data" .. "/packer_compiled.lua",
    },
    aerial = { backends = { "treesitter", "lsp" } },
  },

  -- LuaSnip Options
  luasnip = {
    -- Add paths for including more VS Code style snippets in luasnip
    vscode_snippet_paths = {},
    -- Extend filetypes
    filetype_extend = {
      javascript = { "javascriptreact" },
    },
  },

  -- CMP Source Priorities
  -- modify here the priorities of default cmp sources
  -- higher value == higher priority
  -- The value can also be set to a boolean for disabling default sources:
  -- false == disabled
  -- true == 1000
  cmp = {
    source_priority = {
      nvim_lsp = 1000,
      luasnip = 750,
      buffer = 500,
      path = 250,
    },
  },

  -- Modify which-key registration (Use this with mappings table in the above.)
  ["which-key"] = {
    -- Add bindings which show up as group name
    register_mappings = {
      -- first key is the mode, n == normal mode
      n = {
        -- second key is the prefix, <leader> prefixes
        ["<leader>"] = {
          -- third key is the key to bring up next level and its displayed
          -- group name in which-key top level menu
          ["b"] = { name = "Buffer" },
        },
      },
    },
  },

  -- This function is run last and is a good place to configuring
  -- augroups/autocommands and custom filetypes also this just pure lua so
  -- anything that doesn't fit in the normal config locations above can go here
  polish = function()
    -- Set key binding
    -- Set autocommands
    vim.api.nvim_create_augroup("packer_conf", { clear = true })
    vim.api.nvim_create_autocmd("BufWritePost", {
      desc = "Sync packer after modifying plugins.lua",
      group = "packer_conf",
      pattern = "plugins.lua",
      command = "source <afile> | PackerSync",
    })

    -- Set up custom filetypes
    -- vim.filetype.add {
    --   extension = {
    --     foo = "fooscript",
    --   },
    --   filename = {
    --     ["Foofile"] = "fooscript",
    --   },
    --   pattern = {
    --     ["~/%.config/foo/.*"] = "fooscript",
    --   },
    -- }
  end,
}

return config
```

**Comment by stevearc** [comment] 2022-09-16 14:36
I tried with your `init.lua` and still no repro :(

**Comment by reubenwong97** [comment] 2022-09-16 14:42
oh dear its alright then, thanks so much for trying :)

**Comment by reubenwong97** [comment] 2022-09-16 15:09
hey @stevearc ,

I just stumbled upon a strange thing. If I have another buffer open, then it works fine and I can actually see the symbols outline.

<img width="786" alt="Screenshot 2022-09-16 at 11 07 54 PM" src="https://user-images.githubusercontent.com/26034626/190671277-0a300344-c8f0-4fac-8a5d-f53d27251d05.png">

But once I close that tab, then the error comes back D:

<img width="783" alt="Screenshot 2022-09-16 at 11 08 22 PM" src="https://user-images.githubusercontent.com/26034626/190671373-cf965332-1ed4-4c87-ac4c-f1699ce4c1e9.png">

Otherwise, the only language where it works without additional tabs would be in lua, and I can open up the symbols outline in my `init.lua` just fine.

**Comment by reubenwong97** [comment] 2022-09-17 08:59
Hi @stevearc ,

I figured out how to reproduce the bug! For those times where I had issues opening up the symbols list, I had opened the file after entering vim in tree-view, like `nvim .`, and then selecting the file.

When I open the file directly with `nvim file.py`, then the symbols list opens up fine!

**Comment by stevearc** [comment] 2022-09-17 14:16
Thank you! That was enough for me to reproduce the issue. Traced it back to a bug with the `auto_quit` autocmd in AstroNvim https://github.com/AstroNvim/AstroNvim/issues/975
I believe you can disable auto-quit in the config somewhere, if you want a quick workaround.

For reference, the way I tracked it down after getting the repro was investigating autocmds that I was suspicious of. I would do `:au WinEnter`, see what was there, run `:call nvim_del_augroup_by_name('blah blah')`, then see if the issue still reproduced. After going through `WinEnter` and `BufWinEnter`, I found the culprit on `BufEnter`. Once I deleted the `auto_quit` group, the issue no longer reproduced, and from there it was easy to find the code and figure out what was going wrong.

**Comment by reubenwong97** [comment] 2022-09-17 15:11
Hi @stevearc ,

Thanks for the workaround, and yay glad I managed to stumble upon it too.

Thanks for laying out your steps for debugging the culprit. I'm actually starting to learn lua in hopes of being able to write tools like you do. So this is really helpful :) Thanks for the awesome plugin.

**Closed** 2022-09-24 13:05 UTC
Labels: bug
