### ISSUE TITLE
bug: cannot collapse golang

### ISSUE THREAD

**Issue by imroc** [stevearc/aerial.nvim#286] opened 2023-08-15 02:38 UTC
### Neovim version (nvim -v)

NVIM v0.9.1

### Operating system/version

MacOS 13.5

### Output of :AerialInfo

Aerial Info
-----------
Filetype: go
Configured backends:
  treesitter (supported) (attached)
  lsp (supported)
  markdown (not supported) [Filetype is not markdown]
  man (not supported) [Filetype is not man]
Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct

### Describe the bug

Always expanded in go file, cannot collapse at all:
![image](https://github.com/stevearc/aerial.nvim/assets/7448852/c690c366-6f42-46d5-aeca-3236badd0a49)

### Steps To Reproduce

nvim transport.go

### Expected Behavior

can collapse

**Comment by stevearc** [comment] 2023-08-15 15:57
Duplicate of #206, #194, #81
This is due to the structure of go code. Read those issues for a more in-depth explanation

**Closed by stevearc** 2023-08-15 15:57 UTC
Labels: bug

**Comment by imroc** [comment] 2023-08-18 02:25
Switched to `symbols-outline.nvim`, which can at least fold struct variables.
![image](https://github.com/stevearc/aerial.nvim/assets/7448852/e7303c63-8c21-4df1-a847-5bb19018b1ec)

**Comment by stevearc** [comment] 2023-08-19 22:21
Oh, you just wanted struct fields to be nested? That's easy, aerial just hides Field symbols by default.

```lua
require("aerial").setup({
  filter_kind = false,
  backends = { "lsp", "treesitter" },
})
```

Golang is only weird about nesting when it comes to methods.
