### ISSUE TITLE
Aerial doesn't play well with wfxr/minimap.vim

### ISSUE THREAD

**Issue by joehannes** [stevearc/aerial.nvim#44] opened 2022-01-09 17:23 UTC
**Describe the bug**
When using wfxr/minimap.vim the position/default-direction of the aerial pane is wrong.
In case I put position right: It puts itself to the right of the minimap (which is on the right side already ... and doesn't find symbols and doesn't work - maybe because it is looking into the minimap as source? - and when being closed the minimap pane is resized improperly)
in case i put position left: it puts itself to the right of the buffer (in between buffer and minimap) and works just fine (which is the setup I'm using now, though I wanted to try and put it left and see how I go with that ...)

**System information**
- OS: MacOs Monterey
- Neovim version: 0.6.1
- AerialInfo: 
Filetype: lua
Configured backends:
  lsp (supported) (attached)
  treesitter (supported)
  markdown (not supported) [Filetype is not markdown]
Show symbols: Class, Constructor, Enum, Function, Interface, Method, Struct

**To Reproduce**
1. install wfxr/minimap.vim alongside
2. open the minimap first, then open the aerial pane in any supported filetype buffer
3. see how the aerial window positions itself too far right or unexpectedly to the right instead of to the left, and in case of far right doesn't work/find symbols

If possible, provide a minimal file that will trigger the issue:
sorry, got none ...

**Screenshots**
![8F3B3FD4-F7BB-4908-974C-680B7A106004](https://user-images.githubusercontent.com/63741107/148693165-8e43c24d-492c-4b5f-8784-d46abff1ebd8.png)

**Additional context**
Actually, when I put position left and it works, but positions itself to the right, it only sometimes works.
Sometimes it doesn't find symbols, sometimes it does (don't know exactly).
What might be useful though - is, that if it works (shows symbols) it will first throw this Error and then on user confirmation of the Nvim error it continues to show the symbols:
Error executing vim.schedule lua callback: ...site/pack/packer/start/aerial.nvim/lua/aerial/render.lua:137: attempt to index a nil value
stack traceback:
        ...site/pack/packer/start/aerial.nvim/lua/aerial/render.lua:137: in function 'update_highlights'
        ...site/pack/packer/start/aerial.nvim/lua/aerial/render.lua:97: in function 'update_aerial_buffer'
        ...ck/packer/start/aerial.nvim/lua/aerial/backends/init.lua:91: in function 'set_symbols'
        .../start/aerial.nvim/lua/aerial/backends/lsp/callbacks.lua:71: in function 'handle_symbols'
        .../start/aerial.nvim/lua/aerial/backends/lsp/callbacks.lua:109: in function 'fn'
        vim.lua:415: in function 'cb'
        vim.lua:285: in function <vim.lua:285>

**Comment by stevearc** [comment] 2022-01-10 19:54
The error you're seeing shouldn't cause this behavior, and I've fixed it on the latest master.

I'm honestly not sure what could be causing this issue for you. I tried it out myself and it seemed to work as intended.

https://user-images.githubusercontent.com/506791/148829817-26c482e3-b4a9-4497-95d9-0348a0075fd3.mp4

Do you have autocmds set up that do things when windows are opened or buffers are switched? If you set up an empty neovim config with *only* minimap & aerial do you still see the issue? If so, what is the config that you're passing to `aerial.setup()`?

**Comment by joehannes** [comment] 2022-01-10 22:31
hehey, hurray @stevearc, the error has gone with the latest update :-) it's now working fine ...
I'm still looking into the issue why it's not putting itself on the left side instead

**Comment by joehannes** [comment] 2022-01-10 23:50
ok, I can't figure it out quickly what's going on with the left|right thingy ... I'm just now doing a cleanup on my config, maybe that gets me somewhere ...
if you really want to, you can always checkout [my conifg](https://github.com/joehannes-os/neovim-lua-config)
thx, I guess you can close that for now, I'll reopen/post more comments or so if I find out anything

**Comment by stevearc** [comment] 2022-01-11 00:12
Closing for now, then. Feel free to re-open if you find out what's causing the conflict

**Closed by stevearc** 2022-01-11 00:12 UTC
Labels: bug
