### ISSUE TITLE
Error message on opening a new file when Aerial is open

### ISSUE THREAD

**Issue by vsonicmu** [stevearc/aerial.nvim#172] opened 2022-10-25 12:29 UTC
**Describe the bug**
This happens while working with python (I have not tried other languages). Opening a new file when Aerial is already open causes this error message to pop up. It does not happen when switching to an existing buffer (i.e. an already open file). 

I use the Treesitter backend by default but I also get this error with the LSP backend. 

```
Error executing vim.schedule lua callback: ...site/pack/packer/start/aerial.nvim/lua/aerial/window.lua:461: Invalid buffer id: -1
stack traceback:
        [C]: in function 'nvim_buf_line_count'
        ...site/pack/packer/start/aerial.nvim/lua/aerial/window.lua:461: in function 'update_position'
        ...site/pack/packer/start/aerial.nvim/lua/aerial/window.lua:412: in function 'update_all_positions'
        ...ck/packer/start/aerial.nvim/lua/aerial/backends/init.lua:151: in function 'set_symbols'
        ...tart/aerial.nvim/lua/aerial/backends/treesitter/init.lua:118: in function 'fetch_symbols'
        ...tart/aerial.nvim/lua/aerial/backends/treesitter/init.lua:125: in function 'attach'
        ...ck/packer/start/aerial.nvim/lua/aerial/backends/init.lua:99: in function 'attach'
        ...ck/packer/start/aerial.nvim/lua/aerial/backends/init.lua:125: in function 'get'
        ...ck/packer/start/aerial.nvim/lua/aerial/backends/init.lua:195: in function 'attach'
        ...ack/packer/start/aerial.nvim/lua/aerial/autocommands.lua:81: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>

```
**System information**
- OS: [windows wsl ubuntu ]
- Neovim version: 0.8
- AerialInfo: 
```
Filetype: python
Configured backends:
  treesitter (supported) (attached)
  lsp (not supported) [LSP client not attached]
  markdown (not supported) [Filetype is not markdown]
  man (not supported) [Filetype is not man]
Show symbols: Class, Constructor, Enum, Function, Interface, Module, Method, Struct
```
- Aerial config:
Default config

- Packer
Running this off a minimal config (these are the only installed packages)
```
      use 'wbthomason/packer.nvim'
      use {
          'nvim-treesitter/nvim-treesitter',
          run = ':TSUpdate'
      }
      use {
          'stevearc/aerial.nvim',
          config = function()
              require("aerial").setup()
          end
      }
```

**To Reproduce**
1. Open a python file
2. :AerialOpen
3. Open another python file

**Screenshots**
![image](https://user-images.githubusercontent.com/3785217/197772026-3ca67022-b7b6-46c9-99ba-e6534c0292aa.png)

**Additional context**
This seems to have started this weekend (post the last commit). 

Thank you for all your hard work!

**Comment by qRoC** [comment] 2022-10-25 14:12
Related to #170

**Comment by stevearc** [comment] 2022-10-25 16:24
Thanks for the report; I'm closing as duplicate of #170. Should be fixed now, but discuss on that issue if it's not the case

**Closed by stevearc** 2022-10-25 16:24 UTC
Labels: bug
