### ISSUE TITLE
bug: no function arguments with pyright

### ISSUE THREAD

**Issue by inyutin** [stevearc/aerial.nvim#298] opened 2023-10-04 13:42 UTC
### Neovim version (nvim -v)

v0.9.1

### Operating system/version

TUXEDO OS 2 x86_64 (Ubuntu), Kernel 6.2.0-10018-tuxedo

### Output of :AerialInfo

Aerial Info
-----------
Filetype: python
Configured backends:
  treesitter (supported) (attached)
  lsp (supported)
  markdown (not supported) [Filetype is not markdown]
  man (not supported) [Filetype is not man]
Show symbols: all symbols

### Describe the bug

The problem is that Aerial doesn't show function arguments. The screenshot below should be self-explanatory.

The python function is:
```python
def getenv_mandatory(var_name: str) -> str:
    value = getenv(var_name)
    if value == "":
        value = None

    if value is None and "pytest" not in sys.modules:
        raise MissingEnvironmentVariable(f"{var_name} does not set in environment, but it's mandatory")
    return value or ""
```

Aerial shows:
- getenv_mandatory
--- value
--- value

I would expect var_name there, but it's not.
 
<img width="1273" alt="image" src="https://github.com/stevearc/aerial.nvim/assets/28871177/3b007bd0-398c-4f84-8e18-e5339b23b746">

### Steps To Reproduce

I use pyright as python lsp. pyright version is 1.1.326. nvim is v0.9.1

### Expected Behavior

Aerial shows:
- getenv_mandatory
--- value
--- value

I would expect var_name there, but it's not.

### The configuration of  plugin via Lazy:
```lua
--- @type LazyPluginSpec
local aerial_plugin = {
  'stevearc/aerial.nvim',
  event = "VeryLazy",
  commit = "551a2b679f265917990207e6d8de28018d55f437",
  opts = {
    filter_kind = false,
    layout = {
      placement = "edge",
    },
    attach_mode = "global",
  },
  config = function(_, opts)
    require('aerial').setup(opts)
    vim.keymap.set('n', '<leader>to', ":AerialToggle!<CR>")
  end,
}
```

### Additional context

Thank you for this wonderful plugin.

**Comment by stevearc** [comment] 2023-10-04 15:48
This is a feature request, and a duplicate of #111

**Closed by stevearc** 2023-10-04 15:48 UTC
Labels: bug
