### ISSUE TITLE
Missing symbols with the lsp backend

### ISSUE THREAD

**Issue by fgsch** [stevearc/aerial.nvim#132] opened 2022-08-04 11:10 UTC
**Describe the bug**

Some symbols are missing using the LSP backend and go. 
For comparison, `Telescope lsp_document_symbols` shows both `firstSymbol` and `secondSymbol`.

**System information**
- OS: mac
- Neovim version: 0.7.2
- AerialInfo: 
```
Filetype: go
Configured backends:
  treesitter (not supported) [nvim-treesitter not found]
  lsp (supported) (attached)
  markdown (not supported) [Filetype is not markdown]
Show symbols: all symbols
```
- Aerial config:
```
      require("aerial").setup({
           filter_kind = false,
      })
      require("lspconfig")["gopls"].setup({
         on_attach = function(client, bufnr)
            require("aerial").on_attach(client, bufnr)
         end
      })
```

**To Reproduce**
1. create a main.go file containing:
```
package main

const (
        firstSymbol  = 1
        secondSymbol = 2
)

func main() {
}
```
2. Make sure LSP is attached.
3. Toggle the Aerial window. Only `firstSymbol` is shown.

**Screenshots**

![Screenshot 2022-08-04 at 11 59 53](https://user-images.githubusercontent.com/241785/182832369-5352968d-8841-48b4-ab7e-0d803d2bb1c2.png)

**Comment by stevearc** [comment] 2022-08-04 16:08
Symbols should all display now. There's some additional work that I need to do to fix navigation. The issue is that both of the symbols have the exact same "Range", so the cursor can't tell if it's on the `firstSymbol` or the `secondSymbol`. This can be differentiated using the "SelectionRange", but I'll need to build in support for that.

**Comment by fgsch** [comment] 2022-08-04 22:24
I can confirm I see the symbols now. I will keep an eye for the other fixes.
Thank you!

**Comment by stevearc** [comment] 2022-08-09 05:55
I've also added SelectionRange support to `AerialNext`/`AerialPrev`. Let me know if there are any remaining issues with these types of symbols

**Comment by fgsch** [comment] 2022-08-10 09:35
Thanks for continuing working on this. 
Unfortunately, I found some issues that can be reproduced with the following code:

```
package main

const (
	firstSymbol  = 1
	secondSymbol = 2
)

var (
	thirdSymbol  = 3
	fourthSymbol = 4
)

func main() {
}
```

The order of the third and fourth symbols is reversed, and navigating them from top to bottom or bottom to top shows odd behaviours in both cases. Going from top to bottom, it goes `secondSymbol`, `fourthSymbol`, then `thirdSymbol` but it highlights `secondSymbol`.  And the reverse happens going from bottom to top, cursor is in the `thirdSymbol` but `secondSymbol` is highlighted, etc.

**Comment by stevearc** [comment] 2022-08-10 15:15
Ah, I think this is because the sort function isn't stable. Should be fixed now

**Comment by fgsch** [comment] 2022-08-10 16:08
Yup, looking good. I'd say this ticket is fixed and working as expected 👍 
Thank you!

**Comment by stevearc** [comment] 2022-08-10 16:16
Awesome, glad to hear it!

**Closed by stevearc** 2022-08-10 16:16 UTC
Labels: bug
